spring.application.name=banco-xyz-bff-web
server.port=8091

# HTTPS + certificado (PKCS12 autofirmado academico)
server.ssl.enabled=true
server.ssl.key-store=classpath:keystore.p12
server.ssl.key-store-password=bancoxyz-s5
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=bancoxyz-bff

ms-cuentas.base-url=http://localhost:8090
backend.connect-timeout-ms=2000
backend.read-timeout-ms=3000

# Autenticacion y autorizacion del canal web
bancoxyz.auth.token=token-web-xyz
bancoxyz.auth.canal=WEB
bancoxyz.auth.permisos=CONSULTA_COMPLETA

logging.level.cl.duoc.bancoxyz.bff=INFO
